### ISSUE TITLE
Build the frontend construct of the "Bot-Overview" (no functionality)

### ISSUE THREAD

**Issue by lukashueller** [bptlab/ark_automate#106]
As a user I need an overview page of all my robots. The first step is to build only a frontend construct that visually mirrors the mockup below. The whole functionality will be implemented in the following user stories.

---

### :thought_balloon: &nbsp; Hints & Thoughts

Below you will find a design proposal for the new start page:

![image](https://user-images.githubusercontent.com/36270527/107122835-70b38e80-689a-11eb-9c55-1fdae602941e.png)

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [x] Should include a layout construct for the `robot overview` page in our CI design. 
(maybe 4 robots in rectangular boxes next to each other and 3 below each other).
- [x] For such a cell of this grid (the box that represents a robot), there should already be a dummy component with the required fields and styling. The values are hard coded.
- [x] Such a Box (a cell of the table) should be highlighted in a different color and used to create a new robot. 
Again, hard-coding the frontend is sufficient. The creation of a new bot will be implemented later.

**Comment by kej-jay** [comment]
@lukashueller Maybe only render those boxes for actual bots created? Dynamically rendering the page length would be a great usability feature instead of having the rows hardcoded?
How about a search option to search for robots by name?

**Comment by kej-jay** [comment]
Also, I seem to not quite understand the CoS, could you please explain them to me and/or elaborate on them?

**Comment by lukashueller** [comment]
@kej-jay I hope it is now more understandable? Thank you for the feedback!

**Comment by lukashueller** [comment]
After a vote in the team, it became clear that this would not outdate the issue #39 . We still want to build a small frontend to inform potential users what our product can do.
