### ISSUE TITLE
Implement EDIT robot (open Modeler)

### ISSUE THREAD

**Issue by lukashueller** [bptlab/ark_automate#108]
As a user I would like to open the corresponding robot in the BPMN modeler by clicking on the Edit button.

---

Requires #107 

https://user-images.githubusercontent.com/36270527/107123685-326c9e00-689f-11eb-9a1d-fb3caf4e7b51.mov

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] Should have the routing functionality so that the BPMN Modeler is loaded with the corresponding robot.
- [ ] For this, the corresponding model must be loaded from the database and the rendering in BPMN must be triggered.
- [ ] The routing should be sufficiently tested.
- [ ] a local copy of the SSoT should be created each time it is opened

**Comment by kej-jay** [comment]
Idea for how this could work:
Each edit link navigates to /modeler/ssotId which calls the modeler component with the specific Id of the SSOT. The Modeler Component then makes a backend call to get the BPMN-xml from the backend by passing in the SSOT-Id.
Maybe consider using [this functionality of react router](https://reactrouter.com/web/example/url-params) for this.
