### ISSUE TITLE
Setup Project 

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#11]
As a Team, we'd like to set up a good setup documentation and Node project, react project in our Repository, in order to continue with the other issues.

---

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [x] Folder structure for each technology exists
- [x] Add documentation for setup in Readme
- [x] Everybody has been able to run it locally

**Comment by kej-jay** [comment]
https://www.freecodecamp.org/news/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0/

**Comment by WolfgangDaniel** [comment]
Time spent: 3SP
