### ISSUE TITLE
Implement RENAME robot

### ISSUE THREAD

**Issue by lukashueller** [bptlab/ark_automate#110]
As a user, I would like to be able to rename the robot via a click on the rename-robot button. This can be done by "transforming" the text field into an input field, or a popup is created.

---

requires #107 
---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] After clicking the button and completing the input, the robot name should be updated in the SSoT of the database. 
(It is intended that the global name of the robot is overwritten.)
- [ ] Renaming has been tested.

**Comment by kej-jay** [comment]
https://mongoosejs.com/docs/api/model.html#model_Model.findByIdAndUpdate
