### ISSUE TITLE
Setup automatic documentation

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#14]
As a Team, we'd like to automatically generate our documentation using JSDOC.

---

### :thought_balloon: Hints & Thoughts
https://jsdoc.app/about-getting-started.html
### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [x] Should include an introduction/cheat sheet on how to document using JSDOC
- [ ] Every team member must understand how to do it
- [ ] JSDOC should be set up and accesible
- [ ] document existing code

**Comment by kej-jay** [comment]
https://jsdoc.app/index.html
https://github.com/SoftwareBrothers/better-docs
