### ISSUE TITLE
write SSoT backend tests

### ISSUE THREAD

**Issue by kej-jay** [bptlab/ark_automate#150]
As a developer, I'd like to be sure that I didn't break anything when working with the code, so I would like to have the code covered through tests.

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] All methods called that can be reached from the frontend by calling the `/ssot/` route are covered by tests
- [ ] The tests are using a local copy of a mongoDB instance to not mess with the working database

**Comment by SanJSp** [comment]
usefull tutorials:
https://dev.to/paulasantamaria/testing-node-js-mongoose-with-an-in-memory-database-32np
https://codeutopia.net/blog/2016/06/10/mongoose-models-and-unit-tests-the-definitive-guide/
