### ISSUE TITLE
implement parameter passing to start robot

### ISSUE THREAD

**Issue by kej-jay** [bptlab/ark_automate#164]
As an enduser I would like to pass parameters to the robot at the point of starting the robot.
depends on #8 

---

### :thought_balloon: &nbsp; Hints & Thoughts

- when clicking on the start bot icon, an interface should be prompted which asks the user to input the required fields

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] Prompt user with necessary interface in the web app
- [ ] Enqueue new job object in DB after specifying the parameters.

**Comment by lukashueller** [comment]
Have a look at: https://www.npmjs.com/package/reactjs-popup
