### ISSUE TITLE
Backend Testing

### ISSUE THREAD

**Issue by kej-jay** [bptlab/ark_automate#192]
As a developer I would like to have existing tests which cover all the backend functionality. After establishing a testing basis, we can now build upon this and create multiple more tests.

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] Should cover all routes with tests and cover possible edge-cases
- [ ] Should attempt to call the routes with malformed and/or wrong data to check for error handling

**Comment by SanJSp** [comment]
After a quick consultation with @kej-jay, the malicious data tests will be implemented by model validation tests.

**Comment by SanJSp** [comment]
After a quick consultation with @kej-jay the malicious data tests will be implemented by model validation tests.
