### ISSUE TITLE
Idea: Implement Overview of Robots Running

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#22]
As a ‹role›, I'd like to ‹feature short description› [ , in order to ‹value it adds›. ]

---

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by lukashueller** [comment]
This issue only makes sense from my point of view if the robots are running in the cloud (#20). Since this is not planned in the BP project scope, this issue also falls outside the project scope.
