### ISSUE TITLE
Implement statistics for bots

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#23]
As a ‹role›, I'd like to ‹feature short description› [ , in order to ‹value it adds›. ]

---

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by kej-jay** [comment]
Maybe [Grafana](https://grafana.com/oss/) could be of use here?

**Comment by lukashueller** [comment]
Issue #111  adds basic statistics to the home screen. A more detailed statistical analysis (on a separate interface) is currently out of scope.
