### ISSUE TITLE
Interface to interact with bots

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#25]
As a ‹role›, I'd like to ‹feature short description› [ , in order to ‹value it adds›. ]

---

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by lukashueller** [comment]
Many issues have been created, which define the creation of a welcome screen with all robots. Further interaction with the robots is not planned in the current project scope. Therefore, this issue is closed.
