### ISSUE TITLE
Ensure Usage of Consistent Naming

### ISSUE THREAD

**Issue by WolfgangDaniel** [bptlab/ark_automate#278]
As a developer, I'd like the naming standard camelCase to be used consistently, in order to have code that is easy to read.

---

### :thought_balloon: &nbsp; Hints & Thoughts
There is one exception to this: We agreed on using PascalCase to name component files.
### :question: &nbsp; Additional Questions to Answer / Consider

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [x] Should check for all names that are not written in camelCase and rewrite them in camelCase (in Frontend, Backend, Local Client, Database)
- [x] Should make sure that the naming conventions of file naming are used consistently (Frontend, Backend, Local Client)
- [x] Should check that changes to the code and database have not effected the behavior of the product
- [x] rename all workflow (camelCase) and wiki (Title-Case) files consistently

**Comment by lukashueller** [comment]
From my point of view, I have already prepared a lot here in the refactor folder Structure Issue. The wiki files still need to be renamed and I would ask that anyone of you check the correct naming scheme for all files. Then everything should be perfect!
