### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by WolfgangDaniel** [bptlab/ark_automate#281]
As a developer, I'd like to have a clean documentation, in order to be able to work with the code easily.

---

### :question: &nbsp; Additional Questions to Answer / Consider

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [x] Should update the readme file in the local client repo and in the main repo (make sure everything is up to date)
- [x] Should add documentation to the local client
- [x] Should go through all function and component documentations and check for mistakes and typos
- [x] Should check GitHub pages if documentation is suffiecient and well structure and implement changes if necessary
- [x] Please add documentation here: https://github.com/bptlab/ark_automate/blob/DEV/client/src/utils/robotExecution.jsx

**Comment by SanJSp** [comment]
Updating the ssot wiki is in my opinion also very improtant here
