### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by WolfgangDaniel** [bptlab/ark_automate#282]
As a developer, I'd like to have an updated wiki, in order to only find relevant information about the project quickly.

---

### :thought_balloon: &nbsp; Hints & Thoughts
Check popular open-source projects and steal some quick win ideas we can implement

### :question: &nbsp; Additional Questions to Answer / Consider

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] Should delete files or parts of files that are not needed anymore (have a look at hints and thoughts) -> make sure you extract all the information from these files that is still useful (rule of thumb: everything you can just google is not relevant)
- [ ] Add diagrams from the technical presentation to the wiki
- [ ] Should enrich the architecture text with pointers to the code files or folders that implement specific elements of the architecture.
- [ ] Refactor the structure and naming of the pages in the wiki if needed 
- [ ] Check all final wiki files for typos.

**Comment by SanJSp** [comment]
Updating the ssot wiki is also very important here
