### ISSUE TITLE
Build basic modelling tool

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#3]
As an RPA developer, I'd like to able to visit a modeling site where I can create BPMN models, in order to document my customer's process. 

---

### :thought_balloon: Hints & Thoughts
Check out https://bpmn.io/
- Simple install, should only be able to use it.
Do #2 first or in parallel
### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [x] I can move BPMN activities, events, gateways into the drawing area
- [x] I can connect the BPMN artifacts
- [x] I can move the artifacts in the drawing area

**Comment by kej-jay** [comment]
@lukashueller @WolfgangDaniel Maybe this could help you: https://github.com/bpmn-io/react-bpmn

**Comment by WolfgangDaniel** [comment]
Inspired by https://github.com/Varooneh/reactbpmn

**Comment by WolfgangDaniel** [comment]
Time spent: 3SP
