### ISSUE TITLE
Setup Gitflow branch sturcture

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#34]
As a Team, we'd like to use the [gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) Branchstructure to organize our branches.

---

### :thought_balloon: Hints & Thoughts
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [x] dev branch created
- [x] every team member has understood the gitflow (read the Atlassian documentation)
- [x] first release on master branch with version number

**Comment by kej-jay** [comment]
@SanJSp, In my opinion, it is not of benefit to create the first release anytime soon, while the basic functionality is still not working at least 90% (talking about hardcoded values for XML, etc)
I still think that the Branch structure is created to be used and afaik all team members understood the flow.
Please let me know, if you're fine with closing this issue without publishing the first release or if you want to keep it in the backlog until a release has been published. (Or maybe you even want to create a release anyway?)

Also @lukashueller and @WolfgangDaniel, your opinions are appreciated

**Comment by SanJSp** [comment]
Because of lacking functionality (hard coded values) the acceptance criteria `first release on master branch with version number` is not necessary right now.
