### ISSUE TITLE
Expand XML of moddel by rpa-task and rpa-app

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#38]
As a developer, I'd like to have a selected rpa task and rpa-app represented in the moddels xml.

---

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [x] XML for BPMN has been expanded by app and task fields
- [x] Selection of app and task is represented in xml

**Comment by kej-jay** [comment]
@SanJSp sollte dies nicht automatisch geschlossen sein/werden?

**Comment by SanJSp** [comment]
Sollte, stimmt. Vielleicht ein Bug? Ich schließe es mal
