### ISSUE TITLE
Create Attribute Sideboard

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#4]
As an RPA Developer, I'd like to be able to edit the name of single activities in the drawing area on a sideboard.

---

### :thought_balloon: Hints & Thoughts
Checkout our Mockup
Do #3 first
### :question: Additional Questions to Answer / Consider Maximilian's mesage:

> Ich hab selbst schon mal ne ganze Weile mit bpmn.io gearbeitet und ihn für einen Use-Case angepasst. Die Community ist da sehr aktiv und es gibt auch einige [offizielle Beispiel-Repos](https://github.com/bpmn-io/bpmn-js-examples/), die ziemlich viele Fälle abdecken. Unter anderem auch, wie man das [Attribut-Panel](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel) einbindet, dieses Panel um eigene Elemente [erweitert](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension), oder sogar [eigene Elemente zum Modellieren](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements) hinzufügt. 

---

## :white_check_mark: Conditions of satisfaction

- [ ] When clicking on an activity a sideboard appears and a field name can be edited
- [ ] When changing the name in the field the activity in the BPMN diagram changes

**Comment by kej-jay** [comment]
It would be a consideration to remap the double-click feature of bpmn.js which is currently used to change the name in the modeler, to instead open the sidebar

**Comment by SanJSp** [comment]
@lukashueller @WolfgangDaniel @kej-jay 
Please reconsider this issue. A simpler alternative can be build using the [React properties Panel](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel). This is way simpler and leaves us with less technical dept.

**Comment by SanJSp** [comment]
Issue is complete becasue the user story was fullfield. Although we will change to a simpler sidepanel in the PR for #6
