### ISSUE TITLE
Change RPA Task and App Dropdowns to react select dropdowns

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#42]
As a user, I'd like to input my rpa app and task in a field provided by React Select

---

### :thought_balloon: Hints & Thoughts
Check out React Select
https://react-select.com/home
### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] Should use React Select Input Fields in sidebar
- [ ] All tests must pass
- [ ] Rpa App and Task should still work

**Comment by lukashueller** [comment]
Hi @SanJSp,
what do you mean here? We are currently using the AntD input field. It can also be searched and automatically suggests matching activities. Can the issue be closed?

**Comment by SanJSp** [comment]
It was requested by @kej-jay. I thought it was a better solution, although I did not read that much into it. Maybe Erik can state again his idea behind this. I remember auto-matching was one point of it.
