### ISSUE TITLE
Give donwloadable .robot file a name

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#43]
As a User, I'd like to specify the name of my .robot File before downloading it

---

### :thought_balloon: Hints & Thoughts
Prompt should have similar layout like this one:
![grafik](https://user-images.githubusercontent.com/38314662/101986037-c64d2f80-3c8b-11eb-9dc4-57d00105e831.png)

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] A prompt pops up when clicking the download button where you should enter your filename
- [ ] Entered filename should end up being the name of the file being downloaded

**Comment by kej-jay** [comment]
@lukashueller When running the Bot either in the Cloud or through the Client software, there should in the future not be a need anymore to download the robot file. So we might think about if the download functionality is still needed and therefore this issue too.

**Comment by kej-jay** [comment]
This Issue could be easily done through #110 and by using the robots name from the SSoT. It should therefore only be an additional call and could maybe be combined into that same issue? @lukashueller

**Comment by lukashueller** [comment]
From my point of view, downloading the robot is only a temporary solution in the development process. Therefore, renaming the download-file is not necessary. @kej-jay

**Comment by kej-jay** [comment]
> 
> 
> From my point of view, downloading the robot is only a temporary solution in the development process. Therefore, renaming the download-file is not necessary. @kej-jay

I commented that once before :D But since you left it in, I deleted that comment. But good thing to know, that this issue is now closed 👍 @lukashueller
