### ISSUE TITLE
Create data structure for parser based on BPMN flow and not creation time of activites

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#44]
As a User, I'd like to have my parser generate the code based on the arrows between my BPMN activities not based on the creation time.

---

### :thought_balloon: Hints & Thoughts
This needs restructuring of the parser, I recommend building a linked list for the activities and to gather the data for the links from the JSON. 
### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] Should have every activity represented in the parser as a node
- [ ] Should have every connection between the activities represented in their nodes (parent, child)
- [ ] Parsing should still work
- [ ] When a new activity in the modeler is created, it should be possible to attach it to the start of an already existing process and it should be executed first when running the .robot file.

**Comment by lukashueller** [comment]
This issue is included in the creation of a new SSoT concept (Issue #51 ) and is therefore no longer needed separately.
