### ISSUE TITLE
Add contributing information to README

### ISSUE THREAD

**Issue by lukashueller** [bptlab/ark_automate#50]
As a team, we want to clean up our README, add contributing information and replace `yarn` with `npm`.
---

## :white_check_mark: Conditions of satisfaction
- [x] Should include contributing information
- [x] Update badges
- [x] Should replace `yarn` with `npm` (please check again)
- [x] It should be checked that a new setup is possible with the steps in the README.

**Comment by kej-jay** [comment]
The Heroku Badge is still not working on the main Branch, please check that @lukashueller
