### ISSUE TITLE
Figure out Datastructure for BPMN Model in SSoT

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#51]
As a dev, I'd like to have an idea of how the BPMN model can be represented in the SSoT or in an extra abstraction layer.

---

### :thought_balloon: Hints & Thoughts
Maybe we can think about as an activity as a node, with parents and children. A possibility could be as an extra json.

## :white_check_mark: Conditions of satisfaction

- [x] Should support BPMN activities, gates, and the general flow of a BPMN model -> order of activities should no longer be determined by creation time of the activities
- [x] Should support variables to save and reuse values
- [x] Should have a quickly written down explanation (MD -> linked in our Wiki) of how it works (and share it with the team)

**Comment by lukashueller** [comment]
I think, this issue would be a good one to show at the tech presentation! (Also with #52 if possible)
What do you think @WolfgangDaniel @kej-jay @SanJSp @MaximilianV

**Comment by kej-jay** [comment]
As mentioned by Maximilian we could have a look at Automagica and see what they are writing to json
