### ISSUE TITLE
Implement data structure solution for saving BPMN

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#52]
As a dev, I'd like to use a nice data structure for our BPMN model in our SSoT.

---

### :thought_balloon: Hints & Thoughts  
Dependent on #51 

---

## :white_check_mark: Conditions of satisfaction

- [ ] Should be able to parse code from a BPMN model
- [ ] Should order activities (2->1) correctly even if created in different order (1,2)
- [ ] Supports activities and the BPMN flow (without XOR & AND | #53 #46 )
- [ ] Refactor BPMN-saving to be more modular for upcoming changes

**Comment by lukashueller** [comment]
Will be closed because it was divided into the three issues (#96 #97 #98 ).
