### ISSUE TITLE
Add modify excel activity to catalogue

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#7]
As an RPA Developer, I'd like to modify my excel spreadsheets using an RPA-activity

---

### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [x] Excel can be selected from apps
- [x] Write value can be selected from tasks
- [ ] Hardcoded parameters are being stored in the background
- [ ] XML updates with parameters

**Comment by lukashueller** [comment]
Hi @SanJSp,
what is missing here to move this issue to the DONE column?

**Comment by SanJSp** [comment]
Was simply an accident. It can be moved into done.
