### ISSUE TITLE
CONCEPT: Improving the software interaction process

### ISSUE THREAD

**Issue by lukashueller** [bptlab/ark_automate#91]
As a development team, we want to analyze the entire integration process between the users and the components of the software in order to find missing user stories. In addition, it should help us to better understand the interactions between the components (architecture).  

---

### :thought_balloon: &nbsp; Hints & Thoughts

From my point of view, this issue should be started in pairs, and then discussed with the whole team. Preferably, the PO should also take care of this ticket in order to directly derive the need for the following user stories.

---

## :white_check_mark: &nbsp; Conditions of satisfaction

Answers to the following questions should be provided, which should be summarized in the wiki (MD):  

- [x] Which individual steps occur in the interaction with our software? (Should be represented as a sequence diagram)
- [x] What steps happen in the interaction with the software?  
(Where is an frontend needed for interaction? -> please draft necessary User stories)
- [x] Which steps happen in the software?  
(where is a backend call, parsing etc. needed -> please draft necessary User stories)
- [x] Why do these steps happen in exactly this order? (elaboration for technical presentation)
- [x] Two-sentence answer: What can be achieved with our software at the end of the project?

**Comment by SanJSp** [comment]
Markdown has been added to the [wiki](https://github.com/bptlab/ark_automate/wiki/Vision-on-how-to-use-ark_autoamte).
The product owner has been informed about upcoming user stories and takes care of the customer pitch
